### PR TITLE
[closertotruth] Add new extractor

### PR DESCRIPTION
**Pull request by stevengos**
First time adding an extractor to youtube-dl. Please check if this is OK. This is for solving issue https://github.com/delftswa2016/team-youtube-dl/issues/16

### CODE REVIEW

**Comment by JordenvBreemen** [comment]
I have tried this on a couple of links now for example:

http://closertotruth.com/series/why-cosmic-fine-tuning-demands-explanation

That is unsupported because in your regex you requires both /series and -video-. Is there a reason you did this? Else I think the regex should be allowed to process more types of urls.

**Comment by stevengos** [comment]
On your link no specific video is shown. if you click on a video you can share the video. In the popup of the sharetool, you can vopy the link pointing to the video. Thus http://closertotruth.com/series/why-cosmic-fine-tuning-demands-explanation#video-1928.

This is also the original issuer on proposed the links to these videos. Also, thus far, I have not found any other formats of links dat point directly to a paga with a video directly shown.

**Comment by JordenvBreemen** [comment]
Aah figures I didn't notice the URL was unchanged! I will have a look again then :)

**Comment by JordenvBreemen** [comment]
I removed a print from the code but it seems very nice GJ :+1:  I have tested this in several links all seem to work fine.

I have one question though, in the video title why did you choose to concat the interviewee_name to the video title. Is this because the video title is always "short interview" or "long interview" or do you have other reasons?

**Comment by stevengos** [comment]
let us take for example http://closertotruth.com/series/why-cosmic-fine-tuning-demands-explanation#video-1928. The video I can extract is downloaded trough the API as _a.mov_, thus I have to compose a title myself. When taking (and parsing) that

**Comment by stevengos** [comment]
(mobile phone) website title will only give _Why cosmic finetuning demands explanation_ for every video that falls in this category. It appears that every video has a separate interviewee, so I added the name of him/her to make a clear distinction

**Comment by JordenvBreemen** [comment]
Alright fair enough! Perhaps @rvanbekkum and @sandervdo can have a quick look at this as well. Maybe they see some beauty issues but this looks good to me.

**Comment by sandervdo** [comment]
Yeah I do. There are methods available in the `common.py`, these also take care of error handling. Why calling `re.search` yourself? I think this has to be changed to the available methods.

**Comment by JordenvBreemen** [comment]
I think it's because he does group all the time and the _search_regex_ doesnt allow for that. Might be wrong.

**Comment by sandervdo** [comment]
I see, then we should investigate. If this can be done with the available methods, we should use them as much as possible. If not, our implementation should be as close as possible regarding error handling etc. I think

**Comment by stevengos** [comment]
I agree to change to 'error save' functions provided by youtube-dl, otherwise we have to add some error handling to it ourselfs

**Comment by JordenvBreemen** [comment]
I have replaced two with the function it's supposed to be and it seems to work. I don't think it's needed with the group(1). But I don't know about the group(2). 

@stevengos Why exactly do you do the group(2) (especially the second one)?

Also please rename the variable "m" to something else as it is not really descriptive.

**Comment by stevengos** [comment]
The m.group(2) was for extracting the interviewee's name. It seems to be broken at this point.

**Comment by JordenvBreemen** [comment]
Alright gj, @rvanbekkum any final  remarks before I merge?

@stevengos please squash commits

**Comment by JordenvBreemen** [comment]
@stevengos Please file this to the official repo from a seperate branch with only 1 commit!

**Pull request merged**
