### PR TITLE
Add IE for lcp.fr

### PR DESCRIPTION
**Pull request by sandervdo**
Please check and try to run the test and see if it works.

Possibble enhancements:
- Regex now only considers a fixed json format (marked as TODO in the source).
- Refactoring (@rvanbekkum)

### CODE REVIEW

**Comment by JordenvBreemen** [comment]
Don't forget to remove the dagbladet extractor and squahsh my commits!

I'm going to test this now.

Edit: I removed the dagbladet extractor.

**Comment by sandervdo** [comment]
Good point, thanks for fixing! :+1:

**Comment by JordenvBreemen** [comment]
I tried this link:

http://www.lcp.fr/la-politique-en-video/schwartzenberg-prg-ce-nest-pas-la-peine-que-la-deuxieme-gauche-se-transforme

And the regex doesnt allow this url, is there a reason you changed the regex to this format?

**Comment by sandervdo** [comment]
@JordenvBreemen I did a total rewrite of the regex so that is also supports https:// etc. I had not found any videos with such urls and as far as I know all urls included the 'emission' part. Can you update the regex so that it accepts a number of 'subfolders' before the actual part we are interested in?

Something like `http://lcp.fr/something/something/something/<actual stuff>`

**Comment by JordenvBreemen** [comment]
Alright I have updated the regex I don't think it has to be started with something/something/ etc. I think they can just place vids on their frontage as well that would look like: http://lcp.fr/headlinevideo or lke the one I posted previously. 

I get an error now as well, gonna look into it.

**Comment by sandervdo** [comment]
I'm pretty sure it's because the structure of the frontpage is entirely different. It is not able to extract the clip_id from that regex, meaning that the url found is different (it does not match anymore).

**Comment by rvanbekkum** [comment]
I am fixing some small issues of the extractor. For example some links did not work, because the `clip_id` did not only consist of numbers, but also letters.
Am doing some testing as well to check whether our IE functions correctly.

**Comment by rvanbekkum** [comment]
Have made my final changes such that everything matches the elements mentioned in `CONTRIBUTIONS.md` of the rg3 repository. The included tests have been run successfully.
In addition to the very basic IE functionality, the IE is now able to do the following:
- Check automatically for available formats/qualities (I have limited the IE to the mp4 formats though)
- Check for multiple thumbnails available
- Fixed some small errors for videos embedded on some pages not being supported (some ids can include letters next to numbers for example)
- Not letting failing matches be fatal errors. Instead some embedded urls may refer to other platforms, e.g. dailymotion. In this case the extractor returns this url for the dailymotion extractor to use.

This is ready for a PR to the rg3 repository, but the commits should first probably be squashed as seems to be desired by the youtube-dl maintainers.

**Comment by rvanbekkum** [comment]
Probably the cleanest is to have a single commit named `'[LCP] Add new extractor'`.
This what is also described in `CONTRIBUTIONS.md` on the rg3 repository.
Also add some example links for which the extractor should work so they can check that out.
Further it would be good to not forget to refer to the corresponding issue that described the support request.

**Comment by JordenvBreemen** [comment]
Tested this, works great. You can merge is you ask me (after you squash)!

I suggest @rvanbekkum files the PR (to youtube-dl) as he did the largest contribution to this PR right?

**Pull request merged**
